#
# Your Crowdin credentials
#
"project_id": "617244"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjY1ZWJjZTc5ZWFmZjc1NjIwZTE3OTdiN2VjZmM5OWEyMGRmYmEzOGU5ZDYzNjQ2MTBmNTdkYzVkYTZlYzVlNmM1YzRkMDIyZGI0MjkxZDc4IiwiaWF0IjoxNjk1ODg4OTMxLjIxODg0NywibmJmIjoxNjk1ODg4OTMxLjIxODg0OSwiZXhwIjoxNzI3NDI0OTMxLjE0Mjc0Niwic3ViIjoiMTYwMjgzMTAiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.df0k8sp6E3PtXgWZjLnPLKLKpb0D3q-BRepwWBKFn5joXDBeiSN4qkPZa_BdilFAt6rsSUJ_iq9z28trpDR4SSObZxS5oiaAyt3p1PpZ8GP2k5vWGFNk8jQxxoHFqVRSOyDfds7ctIYOQYyz9CJPRqNDI6IpmLR2KxhcduRchMSwYw54XXOIuSA1bPe9oNUFpW2dXHoDeaD7hCRlUgFaRBjCLg30yspFV-d8FQ7DCjOFNEDnwhvoI1qVYI1c-Hyrmagc0lFTXfPKts0JiDjodme4aSHJXv4I6T8rLlwKoS8A09iV2WGtfJrM9K7fwYhNlk4iM0ZV386qv_KpT7ZYOYBZzH1HnsJJlRlTp0VKTITlxt9qEIb4gQCRrNvyJL6lUpUT5Za7ayDv3l_HbVGnW5aVSmV7Kk-4mr_0_s_xjrVjsB40LYND5jEbhxEvWv14OW-ryRYC_Au3uZG5c2M2U3-egJg3NibtsvGp3suTCA6vb7b0BgMO6gVREQXaAeNB-yGw1b1i9mE5K2FvrM8et9GKyEcDphuvRjHuDJd75XPn4wntWP7adYfFW94dPKqM0Fri83FmKnYmTaG4lcqL2s5ZXYbZdB2Lj8r31LQHpR2n2m7219_QRU2nKuRaIUquyektPSCfFjwgYT8Xdpp8golLq8YJr8VJcD_0t86vQCc"
"base_path": "."
"base_url": "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files:
    - # File 1
        source: "examples/create-react-app/src/locales/en.json"
        translation: "examples/create-react-app/src/locales/%two_letters_code%.json"

    - # File 2
        source: "examples/nextjs-babel/src/locales/en.po"
        translation: "examples/nextjs-babel/src/locales/%two_letters_code%.po"
#files: [
#  {
#    #
#    # Source files filter
#    # e.g. "/resources/en/*.json"
#    #
#    "source": "examples/create-react-app/src/locales/en.json",
#    #
#    # Where translations will be placed
#    # e.g. "/resources/%two_letters_code%/%original_file_name%"
#    #
#    "translation": "examples/create-react-app/src/locales/%two_letters_code%.json",
#  }
#  {
#    #
#    # Source files filter
#    # e.g. "/resources/en/*.json"
#    #
#    "source": "examples/nextjs-babel/src/locales/en.po",
#    #
#    # Where translations will be placed
#    # e.g. "/resources/%two_letters_code%/%original_file_name%"
#    #
#    "translation": "examples/create-react-app/src/locales/%two_letters_code%.po",
#  }
#]